name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        run: docker login registry.digitalocean.com/so-thai -u "${{ secrets.DOCKER_KEY }}" -p "${{ secrets.DOCKER_KEY }}"

      - name: Build Docker Image
        run: docker build -t "registry.digitalocean.com/so-thai/scaffolding-landing:latest" .

      - name: Push Docker Image to Registry
        run: docker push "registry.digitalocean.com/so-thai/scaffolding-landing:latest"

      - name: Trigger Deployment API
        run: curl -X GET "${{ secrets.DEPLOY_URL }}"

      - name: Logout from Registry
        run: docker logout
